# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s `ndarray`s, with the addition being that\
**Tensors can also be used on a GPU to accelerate computing.**

In [3]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [ ]:
x = torch.Tensor(5, 3) # similar to np.empty((5, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [9]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(y)

tensor([[0.3635, 0.0261, 0.3780],
        [0.0348, 0.1365, 0.7651],
        [0.3471, 0.5254, 0.1479],
        [0.7657, 0.8034, 0.3563],
        [0.0611, 0.4186, 0.8978]])


Get its size

In [12]:
print(x.size())

size_tupel = x.size()
print(size_tupel[0])
print(size_tupel[1])

torch.Size([5, 3])
5
3


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [26]:
x = torch.rand(3,5)
print(f"x before in-place modification: \n{x}")
print("After x[1:3] = 2")
x[1:3] = 2 # rij 1 TOT (exclusief) rij 3 -> rij 0 TOT EN MET rij 1
print(x)
# last two rows are set to 2

x before in-place modification: 
tensor([[0.1292, 0.7222, 0.6877, 0.4172, 0.6365],
        [0.5493, 0.6457, 0.9821, 0.2053, 0.0072],
        [0.4671, 0.5263, 0.5591, 0.6168, 0.1054]])
After x[1:3] = 2
tensor([[0.1292, 0.7222, 0.6877, 0.4172, 0.6365],
        [2.0000, 2.0000, 2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.0000, 2.0000]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [27]:
a = torch.Tensor(2,7) # empty tensor
b = torch.FloatTensor(3,1) # empty float tensor
c = torch.LongTensor(5,2,1) # empty long tensor

# fill entire tensor with 7s
a.fill_(7)
print(a)

# a byte tensor is a tensor where every position can take 8-bit values (0-255)
byte_tensor = torch.ByteTensor(5,)
print(byte_tensor)

# try filling byte tensor with 256
# byte_tensor.fill_(256) # overflow!!

# fill middle 3 indices of byte_tensor with ones
byte_tensor[1:4] = 1
print(byte_tensor)

tensor([[7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7.]])
tensor([0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [33]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(f"y = {y}, \nx = {x}")
print(f"x + y = {x + y}")

y = tensor([[0.3021, 0.0871, 0.5372],
        [0.5728, 0.9258, 0.0838],
        [0.9734, 0.8372, 0.0607],
        [0.5304, 0.4488, 0.3672],
        [0.2975, 0.9840, 0.6059]]), 
x = tensor([[0.2461, 0.7113, 0.6335],
        [0.2902, 0.4799, 0.7063],
        [0.3220, 0.1546, 0.7498],
        [0.9692, 0.4251, 0.8293],
        [0.3576, 0.6178, 0.8955]])
x + y = tensor([[0.5483, 0.7984, 1.1708],
        [0.8630, 1.4057, 0.7901],
        [1.2955, 0.9918, 0.8105],
        [1.4996, 0.8739, 1.1965],
        [0.6551, 1.6017, 1.5015]])


### 2.2 Addition: syntax 2

In [34]:
print(torch.add(x, y))

tensor([[0.5483, 0.7984, 1.1708],
        [0.8630, 1.4057, 0.7901],
        [1.2955, 0.9918, 0.8105],
        [1.4996, 0.8739, 1.1965],
        [0.6551, 1.6017, 1.5015]])


### 2.3 Addition: giving an output tensor

In [35]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.5483, 0.7984, 1.1708],
        [0.8630, 1.4057, 0.7901],
        [1.2955, 0.9918, 0.8105],
        [1.4996, 0.8739, 1.1965],
        [0.6551, 1.6017, 1.5015]])


### 2.4 Addition: in-place

adds `x` to `y`

In [36]:
y.add_(x)
print(y)

tensor([[0.5483, 0.7984, 1.1708],
        [0.8630, 1.4057, 0.7901],
        [1.2955, 0.9918, 0.8105],
        [1.4996, 0.8739, 1.1965],
        [0.6551, 1.6017, 1.5015]])


**NOTE**: **Any operation that mutates a tensor in-place is post-fixed with an `_`**. For example: `x.copy_(y)`, `x.t_()`, `x.fill_()` will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [37]:
print(x[:, 1])

tensor([0.7113, 0.4799, 0.1546, 0.4251, 0.6178])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2) with `@` operator or `torch.mm` function 

In [38]:
x = torch.rand(4, 2)
y = torch.rand(4, 2)

# multiplication
print(x * y)
print(torch.mul(x, y))

# in place multiplication
y.mul_(x)
print(y)

# division
print(x / y)
print(torch.div(x, y))

# in place division
y.div_(x)
print(y)

# matrix multiplication
x = torch.rand(2, 3)
y = torch.rand(3, 2)
print(torch.mm(x, y))

# or use the @ operator
print(x @ y)

# in place matrix multiplication is not supported
# x.mm_(y) # error

tensor([[0.1381, 0.3209],
        [0.5305, 0.0080],
        [0.5872, 0.0240],
        [0.2252, 0.3314]])
tensor([[0.1381, 0.3209],
        [0.5305, 0.0080],
        [0.5872, 0.0240],
        [0.2252, 0.3314]])
tensor([[0.1381, 0.3209],
        [0.5305, 0.0080],
        [0.5872, 0.0240],
        [0.2252, 0.3314]])
tensor([[ 1.5471,  1.2877],
        [ 1.2418,  4.3531],
        [ 1.4893, 38.5696],
        [ 1.8029,  1.0212]])
tensor([[ 1.5471,  1.2877],
        [ 1.2418,  4.3531],
        [ 1.4893, 38.5696],
        [ 1.8029,  1.0212]])
tensor([[0.6464, 0.7766],
        [0.8053, 0.2297],
        [0.6715, 0.0259],
        [0.5547, 0.9792]])
tensor([[0.4483, 0.5230],
        [0.8960, 0.6431]])
tensor([[0.4483, 0.5230],
        [0.8960, 0.6431]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [43]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [44]:
b = a.numpy() # convert to ndarray
print(b)
print(f"Type of b: {type(b)}")

[1. 1. 1. 1. 1.]
Type of b: <class 'numpy.ndarray'>


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [ ]:
a.add_(1)
print(a)
print(b) # b reflects the changes made to a, so numpy() didn't make a copy!

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
# numpy -> torch
b = torch.from_numpy(a) 
# compare with a.numpy() 
#   for torch -> numpy

# add 1 to every element in a, storing the result in a
np.add(a, 1, out=a)

# a has changed
print(a)
# b has also changed
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [49]:
# create a tensor of size (5,2) containing ones
x = torch.ones(5, 2)

# convert to numpy array
y = x.numpy()

# convert back to torch tensor
z = torch.from_numpy(y)

## 4 CUDA Tensors

**Tensors can be moved onto GPU** using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():

    print("CUDA is available! Let's use it.")

    x = x.cuda()
    y = y.cuda()
    z = x + y

    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
    
else:

    print("CUDA not available on your machine.")

CUDA not available on your machine.
