# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s `ndarray`s, with the addition being that\
**Tensors can also be used on a GPU to accelerate computing.**

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3) # similar to np.empty((5, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(y)

tensor([[0.4651, 0.5922, 0.2067],
        [0.0992, 0.5992, 0.8338],
        [0.1426, 0.8010, 0.2617],
        [0.5499, 0.4162, 0.0327],
        [0.2902, 0.0364, 0.6429]])


Get its size

In [4]:
print(x.size())

size_tupel = x.size()
print(size_tupel[0])
print(size_tupel[1])

torch.Size([5, 3])
5
3


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x = torch.rand(3,5)
print(f"x before in-place modification: \n{x}")
print("After x[1:3] = 2")
x[1:3] = 2 # rij 1 TOT (exclusief) rij 3 -> rij 0 TOT EN MET rij 1
print(x)
# last two rows are set to 2

x before in-place modification: 
tensor([[0.6235, 0.7759, 0.4733, 0.0932, 0.5539],
        [0.8436, 0.0775, 0.3802, 0.4540, 0.1301],
        [0.4645, 0.4064, 0.8914, 0.5451, 0.4666]])
After x[1:3] = 2
tensor([[0.6235, 0.7759, 0.4733, 0.0932, 0.5539],
        [2.0000, 2.0000, 2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.0000, 2.0000]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [6]:
a = torch.Tensor(2,7) # empty tensor
b = torch.FloatTensor(3,1) # empty float tensor
c = torch.LongTensor(5,2,1) # empty long tensor

# fill entire tensor with 7s
a.fill_(7)
print(a)

# a byte tensor is a tensor where every position can take 8-bit values (0-255)
byte_tensor = torch.ByteTensor(5,)
print(byte_tensor)

# try filling byte tensor with 256
# byte_tensor.fill_(256) # overflow!!

# fill middle 3 indices of byte_tensor with ones
byte_tensor[1:4] = 1
print(byte_tensor)

tensor([[7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7.]])
tensor([0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [7]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(f"y = {y}, \nx = {x}")
print(f"x + y = {x + y}")

y = tensor([[0.8763, 0.5490, 0.0879],
        [0.0923, 0.4596, 0.8314],
        [0.7999, 0.2626, 0.1280],
        [0.3566, 0.5039, 0.5261],
        [0.8975, 0.6345, 0.2790]]), 
x = tensor([[0.6111, 0.7057, 0.0155],
        [0.4760, 0.7464, 0.6731],
        [0.3276, 0.5565, 0.7046],
        [0.0494, 0.8980, 0.4152],
        [0.1765, 0.3914, 0.4462]])
x + y = tensor([[1.4875, 1.2547, 0.1035],
        [0.5683, 1.2060, 1.5046],
        [1.1275, 0.8192, 0.8326],
        [0.4061, 1.4019, 0.9413],
        [1.0740, 1.0259, 0.7252]])


### 2.2 Addition: syntax 2

In [8]:
print(torch.add(x, y))

tensor([[1.4875, 1.2547, 0.1035],
        [0.5683, 1.2060, 1.5046],
        [1.1275, 0.8192, 0.8326],
        [0.4061, 1.4019, 0.9413],
        [1.0740, 1.0259, 0.7252]])


### 2.3 Addition: giving an output tensor

In [9]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.4875, 1.2547, 0.1035],
        [0.5683, 1.2060, 1.5046],
        [1.1275, 0.8192, 0.8326],
        [0.4061, 1.4019, 0.9413],
        [1.0740, 1.0259, 0.7252]])


### 2.4 Addition: in-place

adds `x` to `y`

In [10]:
y.add_(x)
print(y)

tensor([[1.4875, 1.2547, 0.1035],
        [0.5683, 1.2060, 1.5046],
        [1.1275, 0.8192, 0.8326],
        [0.4061, 1.4019, 0.9413],
        [1.0740, 1.0259, 0.7252]])


**NOTE**: **Any operation that mutates a tensor in-place is post-fixed with an `_`**. For example: `x.copy_(y)`, `x.t_()`, `x.fill_()` will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [11]:
print(x[:, 1])

tensor([0.7057, 0.7464, 0.5565, 0.8980, 0.3914])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2) with `@` operator or `torch.mm` function 

In [12]:
x = torch.rand(4, 2)
y = torch.rand(4, 2)

# multiplication
print(x * y)
print(torch.mul(x, y))

# in place multiplication
y.mul_(x)
print(y)

# division
print(x / y)
print(torch.div(x, y))

# in place division
y.div_(x)
print(y)

# matrix multiplication
x = torch.rand(2, 3)
y = torch.rand(3, 2)
print(torch.mm(x, y))

# or use the @ operator
print(x @ y)

# in place matrix multiplication is not supported
# x.mm_(y) # error

tensor([[0.1339, 0.5860],
        [0.1127, 0.0506],
        [0.2205, 0.3208],
        [0.5080, 0.0787]])
tensor([[0.1339, 0.5860],
        [0.1127, 0.0506],
        [0.2205, 0.3208],
        [0.5080, 0.0787]])
tensor([[0.1339, 0.5860],
        [0.1127, 0.0506],
        [0.2205, 0.3208],
        [0.5080, 0.0787]])
tensor([[2.4870, 1.1480],
        [3.2814, 1.4633],
        [2.5596, 2.3710],
        [1.7422, 2.0178]])
tensor([[2.4870, 1.1480],
        [3.2814, 1.4633],
        [2.5596, 2.3710],
        [1.7422, 2.0178]])
tensor([[0.4021, 0.8711],
        [0.3047, 0.6834],
        [0.3907, 0.4218],
        [0.5740, 0.4956]])
tensor([[0.4365, 0.5148],
        [0.3199, 0.4285]])
tensor([[0.4365, 0.5148],
        [0.3199, 0.4285]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [13]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy() # convert to ndarray
print(b)
print(f"Type of b: {type(b)}")

[1. 1. 1. 1. 1.]
Type of b: <class 'numpy.ndarray'>


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [15]:
a.add_(1)
print(a)
print(b) # b reflects the changes made to a, so numpy() didn't make a copy!

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [16]:
import numpy as np
a = np.ones(5)
# numpy -> torch
b = torch.from_numpy(a) 
# compare with a.numpy() 
#   for torch -> numpy

# add 1 to every element in a, storing the result in a
np.add(a, 1, out=a)

# a has changed
print(a)
# b has also changed
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [17]:
# create a tensor of size (5,2) containing ones
x = torch.ones(5, 2)

# convert to numpy array
y = x.numpy()

# convert back to torch tensor
z = torch.from_numpy(y)

## 4 CUDA Tensors

**Tensors can be moved onto GPU** using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [19]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():

    print("CUDA is available! Let's use it.")

    x = x.cuda()
    y = y.cuda()
    z = x + y

    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
    
else:

    print("CUDA not available on your machine.")

if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

CUDA not available on your machine.
tensor([1.], device='mps:0')
